import java.util.HashMap;
import java.util.ArrayList;

/**
 * This class is generated by the env3d plugin to make
 * it easier to work with models.  It scans a model
 * directory for all the obj files and organized them.
 */
public class BongSoon extends GameObject
{
    /**
     * Zero-argument constructor that places the object in location 0, 0, 0
     */
    public BongSoon()
    {
        this(0,0,0);
    }

    /**
     * Parameterized constructor - allows arbitary of object
     */
    public BongSoon(double x, double y, double z)
    {
        setX(x);
        setY(y);
        setZ(z);
        setScale(1);
        setTexture("images/bongsooncrop.jpg");
        setModel("images/bongsooncrop.jpg");
    }

    public void move()
    {
        simpleFPSControl(0.1);
    }
}
